version: "3"
services:
  go-docker-image:
    env_file:
      - .env
    environment:
      - db_host=db
    build: .
    ports:
      - ${port}:${port}
    volumes:
      - ./:/app
    links:
      - db
    depends_on:
      - db
    networks:
      - default


  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - ${db_port}:${db_port}
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: root
      POSTGRES_DB: avito-merchantx
